### ISSUE TITLE
PU-18 Won't boot

### ISSUE THREAD

**Issue by aminoaz1d** [pyroesp/PlayStation-1-Reset-Mod#16]
With the RST line connected on firmware v1.2, my PU-18 board won't boot - it's as if the reset button is being held. If I unplug the reset line, the console boots without issue. I've tested on two boards I assembled and programmed myself - one was new, one was known good (working in a PU-23).

Debug line seem to be showing proper functioning wrt reading controller data

Anyone else reported this?

**Comment by jpaglier** [comment]
I'm dumb - a point was grounding out because of shielding.
