### ISSUE TITLE
Printing PCB

### ISSUE THREAD

**Issue by ijacquez** [pyroesp/PlayStation-1-Reset-Mod#6]
Would these be the right options to print a few PCBs?

![image](https://user-images.githubusercontent.com/283713/67111616-2e88aa00-f18a-11e9-88b7-f0165d0a6f98.png)

Attached is the [GERBER files](https://github.com/pyroesp/PlayStation-1-Reset-Mod/files/3745094/GERBER.zip).

**Comment by pyroesp** [comment]
I don't have all those options when I go for the PCB prototype quote.

This is what I'm going for : 
![image](https://i.imgur.com/a0UKPoY.png)

**Comment by pyroesp** [comment]
Make sure you get the latest version which will hide the JLCPCB order number.
Also, the resistor is gone as it's not needed due to internal pull-up, see #5 .

**Comment by ijacquez** [comment]
Thanks, I'll update.

The 3.5V has changed as well. Will a part list be given as well?

**Comment by pyroesp** [comment]
I'll either add the part list to the readme or add it to a wiki.

**Comment by pyroesp** [comment]
I've added a part list to the readme after the schematic and pcb images.

You need anything else ?

**Comment by ijacquez** [comment]
Thank you. I'll order a batch and make a few to test them out.

I guess for future revisions, it would be nice to have a connector of sorts for the PICkit3

I'll have to see what motherboard I have.

I have a PS3 to PSX adapter, so I'll see if it works.

Thanks.

**Comment by pyroesp** [comment]
@ijacquez : A connector would add cost for a one time thing.
Best way I see how to do it is make your own cable with pogo pins, that's how I'm going to make it.

If the PS3 controller works on the PS1 with that adapter, then that adapter must be "translating" the communication to the PS1 protocol, which means that it should work if the device ID is one of the three programmed in the code.

**Comment by ijacquez** [comment]
Got the PCB, soldered the chip, the cap.

Programming required that I power it through USB (v2.3). That threw me for a loop. I can only at this point erase, program, check blank, and verify. All passed.

What is a good way to test this without directly connecting to the PlayStation?

![image](https://user-images.githubusercontent.com/283713/68550508-3538c480-03b8-11ea-977b-2fd10bef7b16.png)

**Comment by pyroesp** [comment]
Yes for programming, you need to supply the board with voltage.
You'd do that from the pickit 3 programming menu. Probably something I need to add to the readme!

If you want to test the board I would suggest making a test program for it. 
There is no way to test the board out of the PlayStation unfortunately.

**Comment by ijacquez** [comment]
I have made a fairly big mistake with programming the chip.

So when the board needs to be supplied with voltage, does that mean I simply connect the PICkit3's VPP to VDD, then within the programming menu, have the PICkit3 supply the voltage, and set the voltage to ~2.5V?

**Comment by pyroesp** [comment]
No, the VPP of the PICKit3 goes to the VPP/MCLR pin on the back. VPP outputs a higher voltage than VDD when programming, which potentially could damage the PIC microcontroller!

The silkscreen on the back should mention this :
![pcb back](https://raw.githubusercontent.com/pyroesp/PlayStation-1-Reset-Mod/master/pictures/mod/pcb%20-%20bottom.png)


In the advanced mode of MPLAB IPE go to the Power tab. These are my parameters for the 16F18325:
![MPLAB IPE](https://i.imgur.com/7j9zaqf.png)
These parameters should have a default value for the 16F18325, but the thing you might have to check is the usage of high voltage programming and also that checkbox for powering the target with the PICKit3.
The VDD voltage can be either 5V or 3.5V, it doesn't really matter as long as you're programming the PIC when it's not connected to the PlayStation.

Once it is programmed and verified by MPLAB IPE, then you only need to install it in the PlayStation.

**Comment by pyroesp** [comment]
@ijacquez hello, just letting you know that there's a new firmware version available.
https://github.com/pyroesp/PlayStation-1-Reset-Mod/releases/tag/v1.1

There was an error while making the PCB where data and cmd were switched. The new firmware fixes this.
Gerber files are still the same as in v1.0

**Comment by ijacquez** [comment]
Thanks for the heads up. I'll give the project another whirl.

**Comment by pyroesp** [comment]
Since there's nothing new here I'll close this issue.
